### ISSUE TITLE
add support for pills

### ISSUE THREAD

**Issue by zachguo** [mdbootstrap/mdb-ui-kit#539] opened 2015-04-01 20:26 UTC
On [official demo page Nav section](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#nav), `.active` items have blue background which is not consistent with primary color.

**Comment by abhishekbatra** [comment] 2015-05-11 15:00
+1

**Comment by rosskevin** [comment] 2015-11-19 18:47
duplicate of #316

**Closed as completed by rosskevin** 2015-11-19 18:47 UTC
Labels: feature, bootstrap compliance
