### ISSUE TITLE
Flexible card-body height

### ISSUE THREAD

**Issue by ChrisMCMine** [mdbootstrap/mdb-ui-kit#538] opened 2015-03-31 10:19 UTC
My `card-body` displays a block of text underneath the `card-image`. This length of the text block varies but since the card height always equals the card width long text gets pushed out of the card.

Is there any workaround for that behaviour?

**Comment by Streemo** [comment] 2015-06-19 00:21
is there a work around?

**Comment by Streemo** [comment] 2015-06-19 00:41
Yes, there is a work around. Get rid of the 'card-height-indicator' element, and then change the position to "inherit !important" for .card-content... Hope this helps!!!

**Comment by rosskevin** [comment] 2015-11-19 18:28
duplicate of #548

**Closed as completed by rosskevin** 2015-11-19 18:28 UTC
Labels: enhancement
