### ISSUE TITLE
Label does not "float" when setting input value with jquery

### ISSUE THREAD

**Issue by JeffreySyme** [mdbootstrap/mdb-ui-kit#1165] opened 2017-03-20 16:27 UTC
I am using floating labels and when I set the value of an input with jquery its label does not "float." Inspecting the html the form group still has the style "is-empty" applied after the value is set with jquery.

**Comment by FezVrasta** [comment] 2017-03-20 16:28
Dupe of probably one thousands issues, btw, trigger `change` with js manually

**Closed as completed by FezVrasta** 2017-03-20 16:28 UTC
Labels: duplicate
