### ISSUE TITLE
Improve tabs

### ISSUE THREAD

**Issue by turboraccoon** [mdbootstrap/mdb-ui-kit#519] opened 2015-03-21 16:45 UTC
I think it will be good to make tabs like here
https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-tabs

**Comment by simonv3** [comment] 2015-03-23 06:28
:+1:

**Comment by FezVrasta** [comment] 2015-03-24 20:45
duplicate of #220

Thanks for the suggestion!

**Closed as completed by FezVrasta** 2015-03-24 20:45 UTC
Labels: duplicate
