### ISSUE TITLE
Toggle buttons are misaligned

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#765] opened 2015-12-08 11:16 UTC
See http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#forms. The toggle button circle is in the middle when off, and way out of bounds to the right when on.

**Comment by rosskevin** [comment] 2015-12-08 13:03
Duplicate of #737. Please look at open issues first.  This is only a problem with this particular example.

**Closed as completed by rosskevin** 2015-12-08 13:03 UTC
