### ISSUE TITLE
list groups

### ISSUE THREAD

**Issue by xensor** [mdbootstrap/mdb-ui-kit#716] opened 2015-11-07 10:31 UTC
could we make it where if we just use the standard list-group tags it shows the original list-groups as well. instead of unstyled.

**Comment by rosskevin** [comment] 2015-11-19 17:12
I'm unclear about your question.  Please consider submitting a [CodePen test case](http://codepen.io/rosskevin/pen/VvRgrN) to demonstrate what you would like.

**Comment by rosskevin** [comment] 2015-11-19 18:21
duplicate of #578 ?

**Closed as completed by rosskevin** 2015-11-19 18:21 UTC
