### ISSUE TITLE
Icon button class doesn't work well with sized button classes.

### ISSUE THREAD

**Issue by angrybacon** [mdbootstrap/mdb-ui-kit#1213] opened 2017-09-03 11:29 UTC
#### Test Case

https://codepen.io/angrybacon/pen/YxgqVv?editors=1000

#### Summary

Size classes don't work well with `.bmd-btn-icon`. Features such as border radius are overwritten by specificity.

#### Expected result

The combinations `.btn.btn-sm.bmd-btn-icon` and `.btn.btn-lg.bmd-btn-icon` should result in a circle of the appropriate size, like `.btn.bmd-btn-icon` would.

**Comment by FezVrasta** [comment] 2017-09-10 15:53
Closing because it's actually by design, you should use the supported styles, in this case: `bmd-btn-icon-sm` is the only variation allowed by this button.

**Closed as completed by FezVrasta** 2017-09-10 15:53 UTC
Labels: invalid
