### ISSUE TITLE
List group not requiring an icon

### ISSUE THREAD

**Issue by suederade** [mdbootstrap/mdb-ui-kit#752] opened 2015-12-02 17:53 UTC
List groups don't seem to work at all if you don't want an icon which is a huge oversight, in my opinion.

**Comment by rosskevin** [comment] 2015-12-02 18:18
This appears to be a duplicate of #578

Please note that we welcome PRs if you would like to fix this oversight.  I'm full speed ahead on v4 as of this moment.

**Closed as completed by rosskevin** 2015-12-02 18:18 UTC
Labels: duplicate
