### ISSUE TITLE
Ripple effect not working in mobile browsers

### ISSUE THREAD

**Issue by ikshatjain15** [mdbootstrap/mdb-ui-kit#602] opened 2015-05-20 13:12 UTC
I have developed an HTML bootstrap page and tried it running on mobile device browsers for compatibility check, and found that ripple effect on anchor tag, button tag, icons and on tabs are not working. Rest on checkbox, radio button and floating labels are working.
Kindly give me the solution to run my page on mobile browsers as it works on desktop browsers.
link is www.hopeuplives.org/web_app . Run this link on your mobile browser.

**Comment by scorp559** [comment] 2015-08-18 06:42
same problem here in my app

**Comment by Baswazz** [comment] 2015-09-02 10:43
Any update on this? Same here.

**Comment by hadwinzhy** [comment] 2015-09-04 09:01
maybe the same problem with https://github.com/FezVrasta/bootstrap-material-design/issues/424
and i think u can try to use [grunt-autoprefixer](https://github.com/nDmitry/grunt-autoprefixer) for correct prefixes,

**Comment by rosskevin** [comment] 2015-11-19 18:17
duplicate of #424

**Closed as completed by rosskevin** 2015-11-19 18:17 UTC
