### ISSUE TITLE
Dropdown does not work with jQuery 3+

### ISSUE THREAD

**Issue by devilstars** [mdbootstrap/mdb-ui-kit#1207] opened 2017-08-27 17:06 UTC
#### Test Case
https://codepen.io/Simushkin/pen/wqEbBo

#### Summary
Dropdowns does not work with jQuery 3+. Alway get error `Syntax error, unrecognized expression: #`

#### Expected result
Dropdowns have to work with any version of jQuery.

**Comment by FezVrasta** [comment] 2017-08-27 17:44
dupe of some other issue I can't remember, and v3 is not supported anymore anyway

**Closed as completed by FezVrasta** 2017-08-27 17:44 UTC
Labels: v3-deprecated
