### ISSUE TITLE
Wrong navbar height with navbar-text

### ISSUE THREAD

**Issue by PeteDurst** [mdbootstrap/mdb-ui-kit#1139] opened 2017-01-13 06:30 UTC
#### Test Case 
v4 template - http://codepen.io/anon/pen/rjLOOm?editors=1000

#### Summary
Switching width between 1200px and 1199px the navbar height is wrong.

#### Expected result
The navbar height should be 50px. 
It stays 60px because line-height:20px, margin-top:20px and margin-bottom:20px
```
.navbar .navbar-text {
    color: inherit;
    margin-top: 20px;
    margin-bottom: 20px;
}
```

#### Additional Information
Fix: Add following to bootstrap-material-design.css
Line 2257
```
.navbar .navbar-text {
  color: inherit;
  margin-top: 20px;
  margin-bottom: 20px;
  display: block; /*line added*/
}
```
Line 2715 inside @media (max-width: 1199px) {}
```
  .navbar .navbar-text, /*line added*/
  .navbar .navbar-nav > li > a {
    margin: 0; /*line added*/
    padding-top: 15px;
    padding-bottom: 15px;
  }
```

**Comment by matutter** [comment] 2017-01-13 14:10
I also experienced this, `.navbar-brand` also has excess padding when the media width >= 1200px.

**Comment by jatindhankhar** [comment] 2017-07-13 17:04
Sorry to open a old issue
But I can confirm the same bug. Has a fix been added to the upstream? 

Resolution 
`1920 x 768`
![screenshot from 2017-07-13 22-28-09](https://user-images.githubusercontent.com/2412081/28178077-b839e792-681a-11e7-81ad-7f7ceae1c1e2.png)

Resolution 
`1366 x 768`
![screenshot from 2017-07-13 22-32-25](https://user-images.githubusercontent.com/2412081/28178246-59888be4-681b-11e7-85b8-18cab0b859ed.png)


Template used 
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Software Center | Sugar Labs</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Material Design Fonts -->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Bootstrap Material Design -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.min.css" integrity="sha256-X/mlyZAafJ8j5e74pWh4+qNUD1zurCvLA6hODVobQX0=" crossorigin="anonymous" />
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SugarLabs</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
         <ul class="nav navbar-nav navbar-left"> 
             <li> <a href="#">Home</a>
          </ul> 
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <!-- jQuery -->
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <!-- Twitter Bootstrap JS -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <!-- BootStrap Material Design -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.umd.min.js" integrity="sha256-GYcdwXot2kSaBb8kr9o8zDKYBwQ1PCkugjcCYFQS+IA=" crossorigin="anonymous"></script>
</body>

</html>
```

**Comment by FezVrasta** [comment] 2017-07-13 17:09
nope sorry I'm actually waiting for the first beta of Bootstrap to perform an heavy update of the library. Everything is in stand-by for now.

**Comment by jatindhankhar** [comment] 2017-07-13 17:18
No problem. I'll keep an eye on this thread in the mean time.
Thank you for making and maintaining such an awesome project :+1:

**Comment by FezVrasta** [comment] 2017-09-10 16:01
Closing because the template was using the CSS of BS v3 and updating to v3 the markup isn't valid

**Closed as completed by FezVrasta** 2017-09-10 16:01 UTC
Labels: invalid
