### ISSUE TITLE
nav-tabs doesn't have indication of active tab

### ISSUE THREAD

**Issue by guymguym** [mdbootstrap/mdb-ui-kit#357] opened 2015-01-10 17:47 UTC
I was trying to use nav-tabs but there seem to be two issues:
1. all the tabs have a background (primary color) which is very strong, and not compatible with the way nav-pills are shown.
2. active item doesn't show any visual difference from non active items, which is very confusing when used as tabs that switch content.

what is the reason nav-tabs styling is so different from nav-pills or bootstrap's nav-tabs? is there a benefit to this from material design point of view?

thanks!

**Comment by FezVrasta** [comment] 2015-01-10 18:08
Simply they are not yet styled

**Comment by nilsenj** [comment] 2015-01-10 21:00
What about styling search input or inputs with buttons nearby(addon or input groups)?
It looks really ugly(

just try this code 

```
    <div class="col-lg-6">
        <div class="input-group">
  <span class="input-group-btn">
    <button class="btn btn-primary" type="button">Go!</button>
  </span>
            <input type="text" class="form-control" placeholder="Search for...">
        </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
```

**Comment by nilsenj** [comment] 2015-01-10 21:04
and in all projects I'm removing all thoseadditional puddings
for example
.input-group .input-group-btn .btn {
border-radius: 4px;
margin: 0;
padding: 2px 4px;<<----
}

**Comment by nilsenj** [comment] 2015-01-10 21:21
it fixes a little bit)

.input-group .input-group-btn .btn{
margin: 0;
padding: 4px 4px;
bottom: 2px;
}

**Comment by stathism** [comment] 2015-02-18 18:40
I agree with the problem I would love to have the tabs look like they were intended by the material design. Is there an ETA in order to fix the tabs ?

**Comment by FezVrasta** [comment] 2015-03-17 17:18
duplicate of #220

**Closed as completed by FezVrasta** 2015-03-17 17:18 UTC
